### ISSUE TITLE
Possible performance gain by using maxSockets

### ISSUE THREAD

**Issue by Guuz** [GoogleCloudPlatform/appengine-nodejs#34]
Hello,

We are looking to handle many Request Per Second on our app's but until now the `logOneLine()` looked to be a bottleneck. Say that for every request we log one line to app engine. That number could run into the hundreds of simultaneous app engine logging API requests at the same time, all delaying the original response to the client (because logging needs to be done on an active request).

We ran into the same problem for our app because we are doing an external call for every request. What I did not know is that on Node.js 0.10 and lower the default is a max of 5 simultaneous sockets. Any more and it becomes a big queue and all the request get an extremely high latency.
FYI: we are using https://github.com/request/request

Then it dawned on me that the `logOneLine()` probably has the same problem/bottleneck.
Changing the global value `http.globalAgent.maxSockets` in my app does not seem like a elegant solution; every module should configure it for its own scope.

Does it make sense for this module to configure a higher `maxSockets`? I expect much better performance under load that way.

Let me know what you think!

**Comment by rrch** [comment]
I tested it and log rotation does not work, so there seems to be a server-side blocker. No ETA yet.

**Comment by Guuz** [comment]
Hi,
I might be confused here but this is how i understand it:

Logging using a file on disk is the fastest solution and is preferable. But because there is nog log rotation this is not yet possible.

But we can still up the maxSockets right? That should be a small change and greatly increase performance when you log something on every request and have a lot of requests.
We are now actively implementing as few loglines as possible because of this issue.

**Comment by rrch** [comment]
I'll default maxSockets to 100 and make it configurable.

**Comment by Guuz** [comment]
That's sounds good! Thanks!

**Comment by rrch** [comment]
Version 0.3.0 is out.

**Comment by Guuz** [comment]
Nice! :+1: 
I don't see any documentation yet. I'll have a lookt at the code to figure out how to tweak the settings. I'll let you know!

**Comment by rrch** [comment]
To change it to 200:
```
var appengine = require('appengine');
appengine = new appengine.AppEngine({httpAgentMaxSockets: 200});
```

**Comment by Guuz** [comment]
And then in suppose I should put that in a module that is used throughout my app instead of the default appengine object? You can't configure the "global" appengine module that you require.

**Comment by rrch** [comment]
Yes. I think that calling `new appengine.AppEngine(...)` then stashing away the resulting object and using it all over the place is the correct pattern. Initially we defined the APIs as individual functions under `appengine` but that's too inflexible. If I could go back in time, I'd export the constructor (or an equivalent function) and nothing else.

**Comment by Guuz** [comment]
Great! That is not how we implemented it so I will change it. Thanks for the thip!
I'm sure that if you change the readme people will implement it this way from the get go. And maybe you can deprecate the other way in the future. Its only 0.3.0.
