### ISSUE TITLE
Unable to see logs in console

### ISSUE THREAD

**Issue by robdodson** [GoogleCloudPlatform/appengine-nodejs#44]
Apologies in advance for the newb question:

Given the following route, I was expecting to see a log in my local terminal window

```
app.get('/run', function(req, res) {
  appengine.logOneLine(req, 'Just a test message.', appengine.LogLevel.INFO);
  res.send('Running...');
});
```

I've tried running the app with both `gcloud preview app run .` and just `npm start` but neither produces a log in the local terminal. Am I going about this all wrong?

**Comment by nckh** [comment]
Hi,

1. `docker ps -a` to find the containerId where your Node server is running.
2. `docker logs -f -t <containerId>`
This will stream all your console.logs into the terminal window. 

Only caveat is you will have to get the new containerId every time your server restarts.
Hope that helps :)

**Comment by robdodson** [comment]
Thanks @nckh !
